spring:
  application:
    name: activityservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/AiFitness
      database: AiFitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082
