spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5435/fitness
    username: kartikeymishra312
    password: Kartikey123@

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
