spring:
  application:
    name: aiservice

data:
  mongodb:
    uri: mongodb://localhost:27017/airecommedationfitness
    database: airecommedationfitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
